// Tests for the generateSupportedLangs.js command line.

import path from 'path';
import { main as realMain } from './generateSupportedLangs';

const sempleAppDirectory = path.join(__dirname, '../../../test-app');

// History for `process.stdout.write` mock calls.
const logHistory = {
  log: [],
  latest: '',
};

// History for `fs.writeFileSync` mock calls.
const writeFileHistory = {
  log: [],
  latest: null,
};

// Mock for process.stdout.write
const log = (text) => {
  logHistory.latest = text;
  logHistory.log.push(text);
};

// Mock for fs.writeFileSync
const writeFileSync = (filename, content) => {
  const entry = { filename, content };
  writeFileHistory.latest = entry;
  writeFileHistory.log.push(entry);
};

// Main with mocked output
const main = (...parameters) => realMain({
  parameters,
  log,
  writeFileSync,
  pwd: sempleAppDirectory,
});

// Clean up mock histories
afterEach(() => {
  logHistory.log = [];
  logHistory.latest = null;
  writeFileHistory.log = [];
  writeFileHistory.latest = null;
});

describe('help document', () => {
  it('should print help for --help', () => {
    main('--help');
    expect(logHistory.latest).toMatch(
      "generateSupportedLangs.js — Script to generate the 'src/i18n/messages/currentlySupportedLangs.jsx'"
    );
  });

  it('should print help for -h', () => {
    main('-h');
    expect(logHistory.latest).toMatch(
      "generateSupportedLangs.js — Script to generate the 'src/i18n/messages/currentlySupportedLangs.jsx'"
    );
  });
});

describe('generate with three languages', () => {
  main('ar,de,fr_CA'); // German doesn't have a messages file in the `test-app`

  expect(writeFileHistory.log.length).toBe(1);
  expect(writeFileHistory.latest.filename).toBe(`${sempleAppDirectory}/src/i18n/messages/currentlySupportedLangs.jsx`);

  // It should write the file with the following content:
  //  - import 'react-intl/locale-data/ar' and ar.json messages
  //  - import 'react-intl/locale-data/de' without de.json because it doesn't exist in the
  //    test-app/src/i18n/messages directory
  //  - import 'react-intl/locale-data/fr' and fr_CA.json messages
  //  - export the imported locale-data
  expect(writeFileHistory.latest.content).toMatch(`// This file is generated by the "i18n/scripts/generateSupportedLangs.js" script.
import arData from 'react-intl/locale-data/ar';
import './ar.json';
import deData from 'react-intl/locale-data/de';
import frData from 'react-intl/locale-data/fr';
import './fr_CA.json';

export default {
  'ar': arData,
  'de': deData,
  'fr-ca': frData,
};
`);
});
