// This file is generated by the "generateSupportedLangs.js" script.
import arData from 'react-intl/locale-data/ar';
import daData from 'react-intl/locale-data/da';
import deData from 'react-intl/locale-data/de';
import elData from 'react-intl/locale-data/el';
import esData from 'react-intl/locale-data/es';
import faData from 'react-intl/locale-data/fa';
import frData from 'react-intl/locale-data/fr';
import heData from 'react-intl/locale-data/he';
import hiData from 'react-intl/locale-data/hi';
import idData from 'react-intl/locale-data/id';
import itData from 'react-intl/locale-data/it';
import ptData from 'react-intl/locale-data/pt';
import ruData from 'react-intl/locale-data/ru';
import swData from 'react-intl/locale-data/sw';
import teData from 'react-intl/locale-data/te';
import thData from 'react-intl/locale-data/th';
import trData from 'react-intl/locale-data/tr';
import ukData from 'react-intl/locale-data/uk';
import zhData from 'react-intl/locale-data/zh';

export default {
  'ar': arData,
  'da': daData,
  'de': deData,
  'de-de': deData,
  'el': elData,
  'es-419': esData,
  'es-es': esData,
  'fa': faData,
  'fr-ca': frData,
  'he': heData,
  'hi': hiData,
  'id': idData,
  'it-it': itData,
  'pt-br': ptData,
  'pt-pt': ptData,
  'ru': ruData,
  'sw': swData,
  'te': teData,
  'th': thData,
  'tr-tr': trData,
  'uk': ukData,
  'zh-cn': zhData,
};
